version: '3.8'
services:
  cronicle:
    image: bluet/cronicle-docker:latest
    container_name: cronicle
    hostname: cronicle
    environment:
      - TZ=America/Chicago
      # - CRONICLE_base_app_url=http://cronicle/
    ports:
      - "3012:3012"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/cronicle/data:/opt/cronicle/data
      - /docker/cronicle/logs:/opt/cronicle/logs
      - /docker/cronicle/plugins:/opt/cronicle/plugins
      - /docker/cronicle/workloads/app:/app
    restart: unless-stopped
