version: "3.9"
services:

  # init container updates permission
  init:
    image: "ghcr.io/dagu-dev/dagu:latest"
    user: root
    volumes:
      - dagu:/docker/dagu/.dagu
    command: chown -R dagu /docker/dagu/.dagu/

  # ui web server process
  server:
    image: "ghcr.io/dagu-dev/dagu:latest"
    environment:
      - DAGU_PORT=8080
      - DAGU_DAGS=/docker/dagu/.dagu/dags
    restart: unless-stopped
    ports:
      - "8086:8080"
    volumes:
      - dagu:/docker/dagu/.dagu
      - ./dags/:/docker/dagu/.dagu/dags
    depends_on:
      - init

  # scheduler process
  scheduler:
    image: "ghcr.io/dagu-dev/dagu:latest"
    environment:
      - DAGU_DAGS=/docker/dagu/.dagu/dags
    restart: unless-stopped
    volumes:
      - dagu:/docker/dagu/.dagu
      - ./dags/:/docker/dagu/.dagu/dags
    command: dagu scheduler
    depends_on:
      - init

volumes:
  dagu: {}