version: '3.8'
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=password
        volumes:
            - .data:/docker/archive/postgress-db
        ports:
            - 5432:5432
        networks:
            - postgres-db-network
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'test@test.com'
            PGADMIN_DEFAULT_PASSWORD: 'password'
        ports:
            - 16543:80
        volumes:
            - ./servers.json:/pgadmin4/servers.json
        networks:
            - postgres-db-network
networks:
    postgres-db-network:
        driver: bridge
